# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy
from scrapy import Field


class UserItem(scrapy.Item):
    id = Field()
    name = Field()
    avatar_url = Field()
    headline = Field()
    description = Field()
    url = Field()
    url_token = Field()
    gender = Field()
    cover_url = Field()
    type = Field()
    badge = Field()
    answer_count = Field()
    articles_count = Field()
    commercial_question_count = Field()
    favorite_count = Field()
    favorited_count = Field()
    follower_count = Field()
    following_columns_count = Field()
    following_count = Field()
    pins_count = Field()
    question_count = Field()
    thank_from_count = Field()
    thank_to_count = Field()
    thanked_count = Field()
    vote_from_count = Field()
    vote_to_count = Field()
    voteup_count = Field()
    following_favlists_count = Field()
    following_question_count = Field()
    following_topic_count = Field()
    marked_answers_count = Field()
    mutual_followees_count = Field()
    hosted_live_count = Field()
    participated_live_count = Field()
    locations = Field()
    educations = Field()
    employments = Field()


class QuestionItem(scrapy.Item):
    admin_closed_comment = Field()
    answer_count = Field()
    created = Field()
    author = Field()
    follower_count = Field()
    id = Field()
    qu = Field()
    title = Field()
    type = Field()
    url = Field()
    updated_time = Field()
    url_token = Field()


class AnswerItem(scrapy.Item):
    admin_closed_comment = Field()
    annotation_action = Field()
    author = Field()
    can_comment = Field()
    collapse_reason = Field()
    collapsed_by = Field()
    comment_count = Field()
    comment_permission = Field()
    content = Field()
    created_time = Field()
    excerpt = Field()
    extras = Field()
    id = Field()
    is_collapsed = Field()
    is_copyable = Field()
    is_normal = Field()
    mark_infos = Field()
    question = Field()
    relationship = Field()
    reshipment_settings = Field()
    reward_info = Field()
    suggest_edit = Field()
    thumbnail = Field()
    type = Field()
    updated_time = Field()
    url = Field()
    voteup_count = Field()
    url_token = Field()
